#!/bin/bash

set -eu

#DL_DISTs="${@:-nd"

# TODO: wait for nd14.10 being generated
../master/private/slaves.py print_dockers |  while read DL_SLAVE DL_DIST DL_PASSW; do
	# buildbot can't tollerate dots in the names
#	DL_SLAVE=docker-dl-${DL_DIST//./_}
#	DL_PASSW=$(awk -e "/^$DL_SLAVE /{print \$2;}" < ../master/private/slave_passwords)
	DL_APT="" # nothing to add by default BUT
	DL_ANNEX="git-annex"
    # We need standalone build of annex for anything but jessie or newer
	if [ $DL_DIST != 'XXX' ]; then
	   if [ $DL_DIST = 'nd70' ]; then
		DL_APT="RUN echo 'deb http://http.debian.net/debian wheezy-backports main contrib non-free' > /etc/apt/sources.list.d/backports.list; apt-get update; apt-get install -y -t wheezy-backports git"
	   fi
	   DL_ANNEX="git-annex-standalone"
	fi
	sed  -e "s,DL_SLAVE,$DL_SLAVE,g" \
		 -e "s,DL_DIST,$DL_DIST,g" \
		 -e "s,DL_APT,$DL_APT,g" \
		 -e "s,DL_ANNEX,$DL_ANNEX,g" \
		 -e "s,DL_PASSW,$DL_PASSW,g" \
		 < Dockerfile.in >| Dockerfile

	# add --no-cache if complete rebuild is necessary, otherwise it would re-use prev generated
	# containers for each step
	docker build -t datalad_pymvpa/buildbot:slave-$DL_SLAVE . #&& rm Dockerfile

	# can't do below trick if want to use COPY with relative path... not sure what is default dir then
	# - < Dockerfile
done
