FROM neurodebian:DL_DIST
MAINTAINER Yaroslav Halchenko <yoh@datalad.org>

USER root

# Speed up installation using our apt cacher
#RUN mkdir /etc/apt/apt.conf.d/
COPY conf/etc/apt/apt.conf.d/99apt-cacher /etc/apt/apt.conf.d/99apt-cacher
RUN chmod a+r /etc/apt/apt.conf.d/99apt-cacher
# might interfer later with the testing, so -- disable
# ENV http_proxy http://172.17.42.1:3128

DL_APT

# Make deb-src avail
RUN sed -i -e 's,^deb\(.*\),deb\1\ndeb-src\1,g' /etc/apt/sources.list.d/neurodebian.sources.list /etc/apt/sources.list

RUN apt-get update && apt-get install -y -q \
   python-dev \
   python-pip
# For PyMVPA
RUN apt-get build-dep python-mvpa2; apt-get install python-sklearn ; apt-get install python-shogun || :

RUN pip install buildbot-slave
#RUN groupadd -r buildbot && useradd -r -g buildbot buildbot
#RUN mkdir /buildslave && chown buildbot:buildbot /buildslave
RUN groupadd --gid 131 -r buildbot && useradd -m --uid 121 -g buildbot buildbot

# TODO: add backports for wheezy
# Assure popcon doesn't kick in
RUN bash -c "echo 'debconf debconf/frontend select noninteractive' | debconf-set-selections -"

RUN apt-get install -y -q python-pip 
RUN apt-get install -y -q virtualenv || apt-get install -y -q python-virtualenv

# Install datalad dependencies
RUN apt-get install -y -q python-git python-bs4 patool python-testtools python-mock python-joblib
RUN apt-get install -y -q DL_ANNEX 


# Setup init system
COPY 3rd/baseimage-docker/image/bin/my_init /sbin/my_init
RUN apt-get install -y -q python3 runit
RUN mkdir -p /etc/service/buildslave && echo "#!/bin/sh\nsu -c '/usr/local/bin/buildslave start --nodaemon /home/buildbot' buildbot\n" >| /etc/service/buildslave/run && chmod +x /etc/service/buildslave/run
RUN mkdir -p /etc/container_environment && echo -n no > /etc/container_environment/INITRD

RUN apt-get clean

USER buildbot
WORKDIR /home/buildbot
# Prepare system for working with Git
RUN git config --global user.email "test@buildslave.land"
RUN git config --global user.name "Buildbot DL_SLAVE almighty"
RUN buildslave create-slave . 172.17.42.1 DL_SLAVE DL_PASSW

USER root
ENTRYPOINT ["/sbin/my_init"]
