FROM neurodebian:DL_DIST
MAINTAINER Yaroslav Halchenko <yoh@datalad.org>

USER root

# Speed up installation using our apt cacher
#RUN mkdir /etc/apt/apt.conf.d/
COPY conf/etc/apt/apt.conf.d/99apt-cacher /etc/apt/apt.conf.d/99apt-cacher
RUN chmod a+r /etc/apt/apt.conf.d/99apt-cacher
# might interfer later with the testing, so -- disable
# ENV http_proxy http://10.0.42.1:3128

DL_APT

# Make deb-src avail
RUN sed -i -e 's,^deb \(.*\),deb \1\ndeb-src \1,g' /etc/apt/sources.list.d/neurodebian.sources.list /etc/apt/sources.list

# Assure popcon doesn't kick in
RUN bash -c "echo 'debconf debconf/frontend select noninteractive' | debconf-set-selections -"

RUN apt-get update && apt-get install -y -q \
   python-dev \
   python-pip

# TODO:  for nd70 we need to get upgraded pip, otherwise installations fail
# http://smaug.datalad.org:8020/builders/datalad-pr-docker-dl-nd70/builds/557
# for now added upgrade of pip as part of the master.cfg (also moved aside system-wide one iirc)

# For PyMVPA
RUN apt-get build-dep -y -q python-mvpa2; apt-get install -y -q python-sklearn ; apt-get install -y -q python-shogun || :

RUN pip install buildbot-slave
#RUN groupadd -r buildbot && useradd -r -g buildbot buildbot
#RUN mkdir /buildslave && chown buildbot:buildbot /buildslave
RUN groupadd --gid 131 -r buildbot && useradd -m --uid 121 -g buildbot buildbot

# TODO: add backports for wheezy

RUN apt-get install -y -q python-pip python-six python3-six
RUN apt-get install -y -q virtualenv || apt-get install -y -q python-virtualenv

# Install datalad dependencies
RUN apt-get install -y -q python-git python-bs4 patool python-testtools python-mock python-joblib python-rdflib python-dateutil python-requests python-keyring python-boto python-argcomplete python-appdirs python-humanize python-scrapy python-progressbar python-wrapt pandoc
# on nd14.04 need to prune rdflib otherwise env doesn't pick local one but system wide installed one which is too old
RUN [ 'DL_DIST' != 'nd14.04' ] || dpkg --purge python-rdflib 
RUN apt-get install -y -q DL_ANNEX 
# for ultimatedb
RUN apt-get install -y -q python-sqlalchemy


# Setup init system
COPY 3rd/baseimage-docker/image/bin/my_init /sbin/my_init
RUN apt-get install -y -q python3 runit
RUN mkdir -p /etc/service/buildslave && echo "#!/bin/sh\nsu -c '/usr/local/bin/buildslave start --nodaemon /home/buildbot' buildbot\n" >| /etc/service/buildslave/run && chmod +x /etc/service/buildslave/run
RUN mkdir -p /etc/container_environment && echo -n no > /etc/container_environment/INITRD

# Additional pieces
#RUN apt-get install -y -q libffi-dev  # needed for vcr.py's dependecy, failed before on 14.04
# For scrapy and vcr.py
# TODO: on wheezy we pulled in libldap-2.4-2 from backports so backports version of -dev must be installed as well
#       the same for libgpg-error0
# RUN apt-get install -y -q -t wheezy-backports libgpg-error-dev libldap2-dev libp11-kit-dev
# libcurl4-openssl-dev needed for curl-config which is apparently needed while pip installing scrapy
RUN apt-get install -y -q libffi-dev libssl-dev liblzma-dev
# there are conflicts among backports, so let it install "optionally"
RUN apt-get install libcurl4-openssl-dev || :

# Special treatment from Germans to make testing on utf-8 filenames working
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
RUN apt-get install -y -q locales
RUN apt-get clean

USER buildbot
WORKDIR /home/buildbot
# Prepare system for working with Git
RUN git config --global user.email "test@buildslave.land"
RUN git config --global user.name "Buildbot DL_SLAVE almighty"
RUN buildslave create-slave . 10.0.42.1 DL_SLAVE DL_PASSW

USER root
ENTRYPOINT ["/sbin/my_init"]
